name: Deploy to EC2

on:
  push:
    branches:
      - cicd

jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  deploy2:
    runs-on: ubuntu-latest
    needs: deploy1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run a linux command
        run: cat index.html

  deploy3:
    runs-on: ubuntu-latest
    needs: deploy2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run a linux command
        run: ls -la

  deploy4:
    runs-on: ubuntu-latest
    needs: deploy3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run a linux command
        run: cat index.html

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MESSAGE: "deploy job finished successfully!"
