name: Test Slack Notification

on:
  push:
    branches:
      - cicd

jobs:
  slack-test:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MESSAGE: " Test message from GitHub Actions worked!"
